backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

logo_url: https://d33wubrfki0l68.cloudfront.net/6dffd4b982008cce71b2f749584c2c09aaf03613/b79e7/_nuxt/img/logo-cleanprof.7aa60db.png
site_url: https://www.cleanprof.id/

collections:
  - name: 'products'
    label: 'Products'
    folder: 'content/products'
    format: 'frontmatter'
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { 
          label: 'Title (Specification)', name: 'title', widget: 'string',
          hint: 'ex: Hand Sanitizer (60 mL)' 
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Specification', name: 'specification', widget: 'string' }
      - { 
          label: 'Price (Rp.)', name: 'price', widget: 'string', 
          hint: 'Add nominal without the Rp.' 
        }
      - { 
          label: 'Discount', name: 'discount', widget: 'string', required: false,
          hint: 'Nominal or Percentage(%). ex: 12000 or 50%; No discount leave as empty.'
        }
      - { label: 'Link Tokopedia', name: 'linktokped', widget: 'string' }
      - { label: 'Link Shopee', name: 'linkshopee', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'text' }

  - name: 'retailers'
    label: 'Retailers'
    folder: 'content/retailers'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Retailer Name', name: 'retailer', widget: 'string' }
      - { label: 'Retailer Logo', name: 'logo', widget: 'image' }
      - { label: 'Alamat', name: 'alamat', widget: 'string' }
      - { label: 'Telepon', name: 'telepon', widget: 'string' }
      - { label: 'Website', name: 'website', widget: 'string', required: false }

  - name: 'pages'
    label: 'Pages'
    format: 'frontmatter'
    files:
      - label: 'Home Page'
        name: 'home'
        format: 'frontmatter'
        file: 'content/home.md'
        fields:
          - { label: 'First Header', name: 'firstHeader', widget: 'string' }
          - { label: 'Second Header', name: 'secondHeader', widget: 'string', required: false }
          - { label: 'Intro Sentence', name: 'intro', widget: 'string' }
          - { label: 'Promo', name: 'promo', widget: 'string' }

      - label: 'About Page'
        name: 'about'
        format: 'frontmatter'
        file: 'content/about.md'
        fields:
          - { label: 'About Us', name: 'about', widget: 'text' }

      - label: 'Catalog Page'
        name: 'catalog'
        format: 'frontmatter'
        file: 'content/catalog.md'
        fields:
          - { label: 'Catalog Link', name: 'catalog', widget: 'string' }

      - label: 'Contact Page'
        name: 'contact'
        format: 'frontmatter'
        file: 'content/contact.md'
        fields:
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Telepon', name: 'telepon', widget: 'string' }
          - { label: 'Instagram', name: 'instagram', widget: 'string', hint: 'Insert without the @' }
          - { label: 'Facebook', name: 'facebook', widget: 'string' }
          - { label: 'Tokopedia', name: 'tokopedia', widget: 'string' }
          - { label: 'Shopee', name: 'shopee', widget: 'string' }
