backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'products'
    label: 'Products'
    folder: 'content/products'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { 
          label: 'Title (Specification)', name: 'title', widget: 'string',
          hint: 'ex: Hand Sanitizer (60 mL)' 
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Specification', name: 'specification', widget: 'string' }
      - { 
          label: 'Price (Rp.)', name: 'price', widget: 'string', 
          hint: 'Add nominal without the Rp.' 
        }
      - { 
          label: 'Discount', name: 'discount', widget: 'string', required: false,
          hint: 'Nominal or Percentage(%). ex: 12000 or 20%; No discount leave as empty.'
        }
      - { label: 'Link Tokopedia', name: 'linktokped ', widget: 'string' }
      - { label: 'Link Shopee', name: 'linkshopee ', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'text' }

  - name: 'pages'
    label: 'Pages'
    format: 'frontmatter'
    files:
      - label: 'Home Page'
        name: 'home'
        format: 'frontmatter'
        file: 'content/home.md'
        fields:
          - { label: 'First Header', name: 'firstHeader', widget: 'string' }
          - { label: 'Second Header', name: 'secondHeader', widget: 'string' }
          - { label: 'Intro Sentence', name: 'intro', widget: 'string' }
          - { label: 'Promo', name: 'promo', widget: 'string' }
   
